// AUTH STATE CONSTANTS
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AVATAR_SUCCESS = "AVATAR_SUCCESS";
export const AVATAR_FAIL = "AVATAR_FAIL";
export const NAME_UPDATED = "NAME_UPDATED";
export const EMAIL_UPDATED = "EMAIL_UPDATED";
export const PASS_UPDATED = "PASS_UPDATED";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const REMOVE_AVATAR = "REMOVE_AVATAR";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_ADMIN = "SET_ADMIN";
// ROOMS STATE CONSTANTS
export const GET_ROOMS = "GET_ROOMS";
export const CREATE_ROOM = "CREATE_ROOM";
export const JOIN_ROOM = "JOIN_ROOM";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const RESET_ROOMS = "RESET_ROOMS";
export const ROOMS_ERROR = "ROOMS_ERROR";
export const LOAD_ROOM = "LOAD_ROOM";
export const ADD_STUDENT = "ADD_STUDENT";
export const REMOVE_STUDENT = "REMOVE_STUDENT";
export const CLASSNAME_UPDATED = "CLASSNAME_UPDATED";
export const SUBJECT_UPDATED = "SUBJECT_UPDATED";
export const DESCRIPTION_UPDATED = "DESCRIPTION_UPDATED";
export const APPROVE_REQUEST = "APPROVE_REQUEST";
export const DENY_REQUEST = "DENY_REQUEST";
// ALERTS STATE CONSTANTS
export const SHOW_ALERT = "SHOW_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
// MATERIALS STATE CONSTANTS
export const GET_MATERIAL = "GET_MATERIAL";
export const UPLOAD_FILE = "UPLOAD_FILE";
export const DELETE_FILE = "DELETE_FILE";
export const FILE_ERROR = "FILE_ERROR";
export const RESET_MATERIAL = "RESET_MATERIAL";
// TASK STATE CONSTANTS
export const CREATE_TASK = "CREATE_TASK";
export const GET_TASKS = "GET_TASKS";
export const REMOVE_TASK = "REMOVE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const TASK_ERROR = "TASK_ERROR";
export const RESET_TASKS = "RESET_TASKS";
// CHAT STATE CONSTANTS
export const RESET_CHAT = "RESET_CHAT";
export const RESET_MESSAGES = "RESET_MESSAGES";
export const SET_USER = "SET_USER";
export const SET_ROOM = "SET_ROOM";
export const SET_HISTORY = "SET_HISTORY";
export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const NEW_MESSAGE = "NEW_MESSAGE";
export const UPDATE_TIME = "UPDATE_TIME";
